//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.13 at 09:18:37 PM IST 
//


package com.npntraining.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.npntraining.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.npntraining.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataModelGenerator }
     * 
     */
    public DataModelGenerator createDataModelGenerator() {
        return new DataModelGenerator();
    }

    /**
     * Create an instance of {@link TableType }
     * 
     */
    public TableType createTableType() {
        return new TableType();
    }

    /**
     * Create an instance of {@link TableType.Columns }
     * 
     */
    public TableType.Columns createTableTypeColumns() {
        return new TableType.Columns();
    }

    /**
     * Create an instance of {@link DataModelGenerator.Table }
     * 
     */
    public DataModelGenerator.Table createDataModelGeneratorTable() {
        return new DataModelGenerator.Table();
    }

    /**
     * Create an instance of {@link ColumnsType }
     * 
     */
    public ColumnsType createColumnsType() {
        return new ColumnsType();
    }

    /**
     * Create an instance of {@link TablePropertiesType }
     * 
     */
    public TablePropertiesType createTablePropertiesType() {
        return new TablePropertiesType();
    }

    /**
     * Create an instance of {@link BucketingType }
     * 
     */
    public BucketingType createBucketingType() {
        return new BucketingType();
    }

    /**
     * Create an instance of {@link PartitionType }
     * 
     */
    public PartitionType createPartitionType() {
        return new PartitionType();
    }

    /**
     * Create an instance of {@link TableType.Columns.Column }
     * 
     */
    public TableType.Columns.Column createTableTypeColumnsColumn() {
        return new TableType.Columns.Column();
    }

}
