//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.13 at 09:18:37 PM IST 
//


package com.npntraining.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TablePropertiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TablePropertiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="storageFormat" type="{}StorageFormatType"/>
 *         &lt;element name="fieldsTerminator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="collectionItemsTerminator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mapKeyTerminator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="partition" type="{}PartitionType" minOccurs="0"/>
 *         &lt;element name="bucketing" type="{}BucketingType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TablePropertiesType", propOrder = {
    "storageFormat",
    "fieldsTerminator",
    "collectionItemsTerminator",
    "mapKeyTerminator",
    "partition",
    "bucketing"
})
public class TablePropertiesType {

    @XmlElement(required = true)
    protected StorageFormatType storageFormat;
    protected String fieldsTerminator;
    protected String collectionItemsTerminator;
    protected String mapKeyTerminator;
    protected PartitionType partition;
    protected BucketingType bucketing;

    /**
     * Gets the value of the storageFormat property.
     * 
     * @return
     *     possible object is
     *     {@link StorageFormatType }
     *     
     */
    public StorageFormatType getStorageFormat() {
        return storageFormat;
    }

    /**
     * Sets the value of the storageFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link StorageFormatType }
     *     
     */
    public void setStorageFormat(StorageFormatType value) {
        this.storageFormat = value;
    }

    /**
     * Gets the value of the fieldsTerminator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldsTerminator() {
        return fieldsTerminator;
    }

    /**
     * Sets the value of the fieldsTerminator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldsTerminator(String value) {
        this.fieldsTerminator = value;
    }

    /**
     * Gets the value of the collectionItemsTerminator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectionItemsTerminator() {
        return collectionItemsTerminator;
    }

    /**
     * Sets the value of the collectionItemsTerminator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectionItemsTerminator(String value) {
        this.collectionItemsTerminator = value;
    }

    /**
     * Gets the value of the mapKeyTerminator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMapKeyTerminator() {
        return mapKeyTerminator;
    }

    /**
     * Sets the value of the mapKeyTerminator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMapKeyTerminator(String value) {
        this.mapKeyTerminator = value;
    }

    /**
     * Gets the value of the partition property.
     * 
     * @return
     *     possible object is
     *     {@link PartitionType }
     *     
     */
    public PartitionType getPartition() {
        return partition;
    }

    /**
     * Sets the value of the partition property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartitionType }
     *     
     */
    public void setPartition(PartitionType value) {
        this.partition = value;
    }

    /**
     * Gets the value of the bucketing property.
     * 
     * @return
     *     possible object is
     *     {@link BucketingType }
     *     
     */
    public BucketingType getBucketing() {
        return bucketing;
    }

    /**
     * Sets the value of the bucketing property.
     * 
     * @param value
     *     allowed object is
     *     {@link BucketingType }
     *     
     */
    public void setBucketing(BucketingType value) {
        this.bucketing = value;
    }

}
